In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline
import csv as csv
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
import statsmodels
import scipy.stats as stats
import statsmodels.stats.proportion as smpt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier,BaggingClassifier

In [2]:
df=pd.read_csv('Train set values.csv')
df.head()

id  amount_tsh date_recorded        funder  gps_height     installer  \
0  69572      6000.0    2011-03-14         Roman        1390         Roman   
1   8776         0.0    2013-03-06       Grumeti        1399       GRUMETI   
2  34310        25.0    2013-02-25  Lottery Club         686  World vision   
3  67743         0.0    2013-01-28        Unicef         263        UNICEF   
4  19728         0.0    2011-07-13   Action In A           0       Artisan   

   longitude   latitude              wpt_name  num_private  ... payment_type  \
0  34.938093  -9.856322                  none            0  ...     annually   
1  34.698766  -2.147466              Zahanati            0  ...    never pay   
2  37.460664  -3.821329           Kwa Mahundi            0  ...   per bucket   
3  38.486161 -11.155298  Zahanati Ya Nanyumbu            0  ...    never pay   
4  31.130847  -1.825359               Shuleni            0  ...    never pay   

  water_quality quality_group      quantity  quantity_group  \
0          soft          good        enough          enough   
1          soft          good  insufficient    insufficient   
2          soft          good        enough          enough   
3          soft          good           dry             dry   
4          soft          good      seasonal        seasonal   

                 source           source_type  source_class  \
0                spring                spring   groundwater   
1  rainwater harvesting  rainwater harvesting       surface   
2                   dam                   dam       surface   
3           machine dbh              borehole   groundwater   
4  rainwater harvesting  rainwater harvesting       surface   

               waterpoint_type waterpoint_type_group  
0           communal standpipe    communal standpipe  
1           communal standpipe    communal standpipe  
2  communal standpipe multiple    communal standpipe  
3  communal standpipe multiple    communal standpipe  
4           communal standpipe    communal standpipe  

[5 rows x 40 columns]

In [3]:
df.shape

(59400, 40)

In [4]:
pd.set_option('display.max_columns',None)
df.head()

id  amount_tsh date_recorded        funder  gps_height     installer  \
0  69572      6000.0    2011-03-14         Roman        1390         Roman   
1   8776         0.0    2013-03-06       Grumeti        1399       GRUMETI   
2  34310        25.0    2013-02-25  Lottery Club         686  World vision   
3  67743         0.0    2013-01-28        Unicef         263        UNICEF   
4  19728         0.0    2011-07-13   Action In A           0       Artisan   

   longitude   latitude              wpt_name  num_private  \
0  34.938093  -9.856322                  none            0   
1  34.698766  -2.147466              Zahanati            0   
2  37.460664  -3.821329           Kwa Mahundi            0   
3  38.486161 -11.155298  Zahanati Ya Nanyumbu            0   
4  31.130847  -1.825359               Shuleni            0   

                     basin  subvillage   region  region_code  district_code  \
0               Lake Nyasa    Mnyusi B   Iringa           11              5   
1            Lake Victoria     Nyamara     Mara           20              2   
2                  Pangani     Majengo  Manyara           21              4   
3  Ruvuma / Southern Coast  Mahakamani   Mtwara           90             63   
4            Lake Victoria  Kyanyamisa   Kagera           18              1   

         lga        ward  population public_meeting              recorded_by  \
0     Ludewa    Mundindi         109           True  GeoData Consultants Ltd   
1  Serengeti       Natta         280            NaN  GeoData Consultants Ltd   
2  Simanjiro     Ngorika         250           True  GeoData Consultants Ltd   
3   Nanyumbu    Nanyumbu          58           True  GeoData Consultants Ltd   
4    Karagwe  Nyakasimbi           0           True  GeoData Consultants Ltd   

  scheme_management                  scheme_name permit  construction_year  \
0               VWC                        Roman  False               1999   
1             Other                          NaN   True               2010   
2               VWC  Nyumba ya mungu pipe scheme   True               2009   
3               VWC                          NaN   True               1986   
4               NaN                          NaN   True                  0   

  extraction_type extraction_type_group extraction_type_class management  \
0         gravity               gravity               gravity        vwc   
1         gravity               gravity               gravity        wug   
2         gravity               gravity               gravity        vwc   
3     submersible           submersible           submersible        vwc   
4         gravity               gravity               gravity      other   

  management_group         payment payment_type water_quality quality_group  \
0       user-group    pay annually     annually          soft          good   
1       user-group       never pay    never pay          soft          good   
2       user-group  pay per bucket   per bucket          soft          good   
3       user-group       never pay    never pay          soft          good   
4            other       never pay    never pay          soft          good   

       quantity quantity_group                source           source_type  \
0        enough         enough                spring                spring   
1  insufficient   insufficient  rainwater harvesting  rainwater harvesting   
2        enough         enough                   dam                   dam   
3           dry            dry           machine dbh              borehole   
4      seasonal       seasonal  rainwater harvesting  rainwater harvesting   

  source_class              waterpoint_type waterpoint_type_group  
0  groundwater           communal standpipe    communal standpipe  
1      surface           communal standpipe    communal standpipe  
2      surface  communal standpipe multiple    communal standpipe  
3  groundwater  communal standpipe multiple    communal standpipe 

In [5]:
# df['num_private'].value_counts()

In [6]:
df['waterpoint_type_group'].value_counts()

communal standpipe    34625
hand pump             17488
other                  6380
improved spring         784
cattle trough           116
dam                       7
Name: waterpoint_type_group, dtype: int64

In [7]:
# df.isnull().sum()

In [8]:
df.drop(['date_recorded','funder','installer','region','scheme_management','management','payment','source','longitude','latitude','public_meeting','permit','wpt_name','subvillage','lga','ward','recorded_by','scheme_name'],axis=1,inplace=True)

In [9]:
# df['num_private'].value_counts()

In [10]:
df.shape

(59400, 22)

In [11]:
df.head(2)

id  amount_tsh  gps_height  num_private          basin  region_code  \
0  69572      6000.0        1390            0     Lake Nyasa           11   
1   8776         0.0        1399            0  Lake Victoria           20   

   district_code  population  construction_year extraction_type  \
0              5         109               1999         gravity   
1              2         280               2010         gravity   

  extraction_type_group extraction_type_class management_group payment_type  \
0               gravity               gravity       user-group     annually   
1               gravity               gravity       user-group    never pay   

  water_quality quality_group      quantity quantity_group  \
0          soft          good        enough         enough   
1          soft          good  insufficient   insufficient   

            source_type source_class     waterpoint_type waterpoint_type_group  
0                spring  groundwater  communal standpipe    communal standpipe  
1  rainwater harvesting      surface  communal standpipe    communal standpipe

In [12]:
l=pd.read_csv("Train set data labels.csv")
l.head()

id    status_group
0  69572      functional
1   8776      functional
2  34310      functional
3  67743  non functional
4  19728      functional

In [13]:
df=pd.concat((df,l),axis=1,sort=False)

In [14]:
df.shape

(59400, 24)

In [15]:
df.drop('id',axis=1,inplace=True)

In [16]:
df.shape

(59400, 22)

In [17]:
l['status_group'].value_counts()

functional                 32259
non functional             22824
functional needs repair     4317
Name: status_group, dtype: int64

In [18]:
df.shape

(59400, 22)

In [19]:
df.head()

amount_tsh  gps_height  num_private                    basin  region_code  \
0      6000.0        1390            0               Lake Nyasa           11   
1         0.0        1399            0            Lake Victoria           20   
2        25.0         686            0                  Pangani           21   
3         0.0         263            0  Ruvuma / Southern Coast           90   
4         0.0           0            0            Lake Victoria           18   

   district_code  population  construction_year extraction_type  \
0              5         109               1999         gravity   
1              2         280               2010         gravity   
2              4         250               2009         gravity   
3             63          58               1986     submersible   
4              1           0                  0         gravity   

  extraction_type_group extraction_type_class management_group payment_type  \
0               gravity               gravity       user-group     annually   
1               gravity               gravity       user-group    never pay   
2               gravity               gravity       user-group   per bucket   
3           submersible           submersible       user-group    never pay   
4               gravity               gravity            other    never pay   

  water_quality quality_group      quantity quantity_group  \
0          soft          good        enough         enough   
1          soft          good  insufficient   insufficient   
2          soft          good        enough         enough   
3          soft          good           dry            dry   
4          soft          good      seasonal       seasonal   

            source_type source_class              waterpoint_type  \
0                spring  groundwater           communal standpipe   
1  rainwater harvesting      surface           communal standpipe   
2                   dam      surface  communal standpipe multiple   
3              borehole  groundwater  communal standpipe multiple   
4  rainwater harvesting      surface           communal standpipe   

  waterpoint_type_group    status_group  
0    communal standpipe      functional  
1    communal standpipe      functional  
2    communal standpipe      functional  
3    communal standpipe  non functional  
4    communal standpipe      functional

In [20]:
df.isnull().sum()

amount_tsh               0
gps_height               0
num_private              0
basin                    0
region_code              0
district_code            0
population               0
construction_year        0
extraction_type          0
extraction_type_group    0
extraction_type_class    0
management_group         0
payment_type             0
water_quality            0
quality_group            0
quantity                 0
quantity_group           0
source_type              0
source_class             0
waterpoint_type          0
waterpoint_type_group    0
status_group             0
dtype: int64

In [21]:
# df['public_meeting'].value_counts()

In [22]:
# df['public_meeting'].fillna(value='True',inplace=True)

In [23]:
# df['public_meeting'].value_counts()

In [24]:
# df['scheme_management'].value_counts()

In [25]:
# df['scheme_management'].fillna(value='VWC',inplace=True)

In [26]:
# df['scheme_management'].value_counts()

In [27]:
# df['permit'].value_counts()

In [28]:
# df['permit'].fillna(value='True',inplace=True)

In [29]:
# df['permit'].value_counts()

In [30]:
# df.dropna(axis=0,inplace=True)

In [31]:
df.shape

(59400, 22)

In [32]:
# df['public_meeting'].replace(to_replace=np.nan,value='True',inplace=True)

In [33]:
# df['public_meeting'].value_counts()

In [34]:
df.isnull().sum()

amount_tsh               0
gps_height               0
num_private              0
basin                    0
region_code              0
district_code            0
population               0
construction_year        0
extraction_type          0
extraction_type_group    0
extraction_type_class    0
management_group         0
payment_type             0
water_quality            0
quality_group            0
quantity                 0
quantity_group           0
source_type              0
source_class             0
waterpoint_type          0
waterpoint_type_group    0
status_group             0
dtype: int64

In [35]:
df['status_group'].replace(to_replace=['functional','non functional','functional needs repair'],value=[1,2,3],inplace=True)

In [36]:
df['status_group'].value_counts()

1    32259
2    22824
3     4317
Name: status_group, dtype: int64

In [37]:
# X.columns

In [38]:
df.describe(include='O')

basin extraction_type extraction_type_group  \
count           59400           59400                 59400   
unique              9              18                    13   
top     Lake Victoria         gravity               gravity   
freq            10248           26780                 26780   

       extraction_type_class management_group payment_type water_quality  \
count                  59400            59400        59400         59400   
unique                     7                5            7             8   
top                  gravity       user-group    never pay          soft   
freq                   26780            52490        25348         50818   

       quality_group quantity quantity_group source_type source_class  \
count          59400    59400          59400       59400        59400   
unique             6        5              5           7            3   
top             good   enough         enough      spring  groundwater   
freq           50818    33186          33186       17021        45794   

           waterpoint_type waterpoint_type_group  
count                59400                 59400  
unique                   7                     6  
top     communal standpipe    communal standpipe  
freq                 28522                 34625

In [39]:
df_new=pd.get_dummies(data=df,columns=['basin','extraction_type','extraction_type_group','extraction_type_class','management_group','payment_type','water_quality','quality_group','quantity',
                                'quantity_group','source_type','source_class','waterpoint_type','waterpoint_type_group'],drop_first=True)

In [40]:
df_new.shape

(59400, 100)

In [41]:
df_new.head(2)

amount_tsh  gps_height  num_private  region_code  district_code  \
0      6000.0        1390            0           11              5   
1         0.0        1399            0           20              2   

   population  construction_year  status_group  basin_Lake Nyasa  \
0         109               1999             1                 1   
1         280               2010             1                 0   

   basin_Lake Rukwa  basin_Lake Tanganyika  basin_Lake Victoria  \
0                 0                      0                    0   
1                 0                      0                    1   

   basin_Pangani  basin_Rufiji  basin_Ruvuma / Southern Coast  \
0              0             0                              0   
1              0             0                              0   

   basin_Wami / Ruvu  extraction_type_cemo  extraction_type_climax  \
0                  0                     0                       0   
1                  0                     0                       0   

   extraction_type_gravity  extraction_type_india mark ii  \
0                        1                              0   
1                        1                              0   

   extraction_type_india mark iii  extraction_type_ksb  extraction_type_mono  \
0                               0                    0                     0   
1                               0                    0                     0   

   extraction_type_nira/tanira  extraction_type_other  \
0                            0                      0   
1                            0                      0   

   extraction_type_other - mkulima/shinyanga  \
0                                          0   
1                                          0   

   extraction_type_other - play pump  extraction_type_other - rope pump  \
0                                  0                                  0   
1                                  0                                  0   

   extraction_type_other - swn 81  extraction_type_submersible  \
0                               0                            0   
1                               0                            0   

   extraction_type_swn 80  extraction_type_walimi  extraction_type_windmill  \
0                       0                       0                         0   
1                       0                       0                         0   

   extraction_type_group_gravity  extraction_type_group_india mark ii  \
0                              1                                    0   
1                              1                                    0   

   extraction_type_group_india mark iii  extraction_type_group_mono  \
0                                     0                           0   
1                                     0                           0   

   extraction_type_group_nira/tanira  extraction_type_group_other  \
0                                  0                            0   
1                                  0                            0   

   extraction_type_group_other handpump  \
0                                     0   
1                                     0   

   extraction_type_group_other motorpump  extraction_type_group_rope pump  \
0                                      0                                0   
1                                      0                                0   

   extraction_type_group_submersible  extraction_type_group_swn 80  \
0                                  0                             0   
1                                  0                             0   

   extraction_type_group_wind-powered  extraction_type_class_handpump  \
0                                   0                               0   
1                                   0                               0   

   extraction_type_class_motorpump  extraction_type_class_other  \
0                                0                            0   
1   

In [42]:
df_new.drop('extraction_type_other - mkulima/shinyanga',axis=1,inplace=True)

In [43]:
X=df_new.drop('status_group',axis=1)
y=df_new['status_group']

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
sc=StandardScaler()

In [46]:
X_sc=pd.DataFrame(sc.fit_transform(X),columns=X.columns)

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X_sc, y, test_size=0.33, random_state=42)

In [48]:
X_train.shape

(39798, 98)

In [49]:
y_train.shape

(39798,)

In [50]:
X_test.shape

(19602, 98)

In [51]:
y_test.shape

(19602,)

### Model Building

In [52]:
lr=LogisticRegression(max_iter=100000)
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [53]:
pred_lr=lr.predict(X_test)

In [54]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           1       0.70      0.91      0.79     10719
           2       0.78      0.59      0.68      7458
           3       0.47      0.02      0.03      1425

    accuracy                           0.72     19602
   macro avg       0.65      0.50      0.50     19602
weighted avg       0.71      0.72      0.69     19602



In [55]:
print(confusion_matrix(y_test,pred_lr))

[[9704 1004   11]
 [3020 4424   14]
 [1187  216   22]]


In [56]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [57]:
pred_rf=rf.predict(X_test)

In [58]:
print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           1       0.79      0.86      0.83     10719
           2       0.81      0.75      0.78      7458
           3       0.48      0.33      0.39      1425

    accuracy                           0.78     19602
   macro avg       0.69      0.65      0.67     19602
weighted avg       0.78      0.78      0.78     19602



In [59]:
print(confusion_matrix(y_test,pred_rf))

[[9252 1099  368]
 [1694 5611  153]
 [ 733  219  473]]


In [60]:
ada=AdaBoostClassifier(base_estimator=rf)
ada.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         max_samples=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                       

In [61]:
pred_ada=ada.predict(X_test)

In [62]:
print(classification_report(y_test,pred_ada))

              precision    recall  f1-score   support

           1       0.79      0.85      0.82     10719
           2       0.80      0.76      0.78      7458
           3       0.47      0.36      0.41      1425

    accuracy                           0.78     19602
   macro avg       0.69      0.65      0.67     19602
weighted avg       0.77      0.78      0.78     19602



In [63]:
print(confusion_matrix(y_test,pred_ada))

[[9151 1171  397]
 [1657 5632  169]
 [ 718  201  506]]


In [64]:
gbc=GradientBoostingClassifier()
gbc.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [65]:
pred_gbc=gbc.predict(X_test)

In [66]:
print(classification_report(y_test,pred_gbc))

              precision    recall  f1-score   support

           1       0.72      0.92      0.81     10719
           2       0.82      0.62      0.71      7458
           3       0.57      0.11      0.18      1425

    accuracy                           0.75     19602
   macro avg       0.70      0.55      0.57     19602
weighted avg       0.75      0.75      0.72     19602



In [67]:
print(confusion_matrix(y_test,pred_gbc))

[[9869  783   67]
 [2785 4625   48]
 [1047  224  154]]


In [68]:
import xgboost as xgb
xgbc=xgb.XGBClassifier()

In [69]:
xgbc.fit(X_train, y_train) 

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [70]:
pred_xgbc=xgbc.predict(X_test)

In [71]:
print(classification_report(y_test,pred_xgbc))

              precision    recall  f1-score   support

           1       0.77      0.90      0.83     10719
           2       0.83      0.72      0.78      7458
           3       0.60      0.24      0.34      1425

    accuracy                           0.79     19602
   macro avg       0.74      0.62      0.65     19602
weighted avg       0.78      0.79      0.78     19602



In [72]:
print(confusion_matrix(y_test,pred_xgbc))

[[9687  878  154]
 [1980 5406   72]
 [ 884  202  339]]


In [73]:
df_t=pd.read_csv("Test set values.csv")
df_t.head()

id  amount_tsh date_recorded                  funder  gps_height  \
0  50785         0.0    2013-02-04                    Dmdd        1996   
1  51630         0.0    2013-02-04  Government Of Tanzania        1569   
2  17168         0.0    2013-02-01                     NaN        1567   
3  45559         0.0    2013-01-22              Finn Water         267   
4  49871       500.0    2013-03-27                  Bruder        1260   

    installer  longitude   latitude                 wpt_name  num_private  \
0        DMDD  35.290799  -4.059696  Dinamu Secondary School            0   
1         DWE  36.656709  -3.309214                  Kimnyak            0   
2         NaN  34.767863  -5.004344           Puma Secondary            0   
3  FINN WATER  38.058046  -9.418672           Kwa Mzee Pange            0   
4      BRUDER  35.006123 -10.950412          Kwa Mzee Turuka            0   

                     basin  subvillage   region  region_code  district_code  \
0                 Internal      Magoma  Manyara           21              3   
1                  Pangani     Kimnyak   Arusha            2              2   
2                 Internal       Msatu  Singida           13              2   
3  Ruvuma / Southern Coast  Kipindimbi    Lindi           80             43   
4  Ruvuma / Southern Coast     Losonga   Ruvuma           10              3   

             lga          ward  population public_meeting  \
0          Mbulu        Bashay         321           True   
1   Arusha Rural      Kimnyaki         300           True   
2  Singida Rural          Puma         500           True   
3         Liwale       Mkutano         250            NaN   
4         Mbinga  Mbinga Urban          60            NaN   

               recorded_by scheme_management     scheme_name permit  \
0  GeoData Consultants Ltd        Parastatal             NaN   True   
1  GeoData Consultants Ltd               VWC  TPRI pipe line   True   
2  GeoData Consultants Ltd               VWC               P    NaN   
3  GeoData Consultants Ltd               VWC             NaN   True   
4  GeoData Consultants Ltd       Water Board          BRUDER   True   

   construction_year extraction_type extraction_type_group  \
0               2012           other                 other   
1               2000         gravity               gravity   
2               2010           other                 other   
3               1987           other                 other   
4               2000         gravity               gravity   

  extraction_type_class   management management_group      payment  \
0                 other   parastatal       parastatal    never pay   
1               gravity          vwc       user-group    never pay   
2                 other          vwc       user-group    never pay   
3                 other          vwc       user-group      unknown   
4               gravity  water board       user-group  pay monthly   

  payment_type water_quality quality_group      quantity quantity_group  \
0    never pay          soft          good      seasonal       seasonal   
1    never pay          soft          good  insufficient   insufficient   
2    never pay          soft          good  insufficient   insufficient   
3      unknown          soft          good           dry            dry   
4      monthly          soft          good        enough         enough   

                 source           source_type source_class  \
0  rainwater harvesting  rainwater harvesting      surface   
1                spring                spring  groundwater   
2  rainwater harvesting  rainwater harvesting      surface   
3          shallow well          shallow well  groundwater   
4                spring                spring  groundwater   

      waterpoint_type waterpoint_type_group  
0               other                 other  
1  communal standpipe    communal standpipe  
2               other                 other  
3               other      

In [74]:
df_t.shape

(14850, 40)

In [75]:
df_t.drop(['date_recorded','funder','installer','region','scheme_management','management','payment','source','longitude','latitude','public_meeting','permit','wpt_name','subvillage','lga','ward','recorded_by','scheme_name'],axis=1,inplace=True)

In [76]:
df_t.shape

(14850, 22)

In [77]:
a=df_t['id']

In [78]:
df_t.isnull().sum()

id                       0
amount_tsh               0
gps_height               0
num_private              0
basin                    0
region_code              0
district_code            0
population               0
construction_year        0
extraction_type          0
extraction_type_group    0
extraction_type_class    0
management_group         0
payment_type             0
water_quality            0
quality_group            0
quantity                 0
quantity_group           0
source_type              0
source_class             0
waterpoint_type          0
waterpoint_type_group    0
dtype: int64

In [79]:
df_new_t=pd.get_dummies(data=df_t,columns=['basin','extraction_type','extraction_type_group','extraction_type_class','management_group','payment_type','water_quality','quality_group','quantity',
                                'quantity_group','source_type','source_class','waterpoint_type','waterpoint_type_group'],drop_first=True)

In [80]:
df_new_t.shape

(14850, 99)

In [81]:
df_new_t=df_new_t.drop(['id'],axis=1)

In [82]:
X_t_sc=pd.DataFrame(sc.fit_transform(df_new_t),columns=df_new_t.columns)

In [83]:
pred_xgbc1=xgbc.predict(X_t_sc)

In [84]:
pred_xgbc1

array([1, 1, 1, ..., 1, 1, 2], dtype=int64)

In [85]:
dataframe=pd.DataFrame()

In [86]:
dataframe['id']=pd.Series(a)

In [87]:
dataframe['status_group']=pd.Series(pred_xgbc1)

In [88]:
dataframe['status_group'].replace(to_replace=[1,2,3],value=['functional','non functional','functional needs repair'],inplace=True)

In [89]:
dataframe

id    status_group
0      50785      functional
1      51630      functional
2      17168      functional
3      45559  non functional
4      49871      functional
...      ...             ...
14845  39307  non functional
14846  18990      functional
14847  28749      functional
14848  33492      functional
14849  68707  non functional

[14850 rows x 2 columns]

In [90]:
dataframe.to_csv (r'C:\Users\lenovo\Desktop\Python\Driven Data\Water\git-sub.csv', index = False)